_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 9
                - 103
                - 105
            "2":
                - 1
                - 9
                - 103
                - 105
            "3":
                - 7
                - 13
                - 16
                - 55
                - 66
            "4": 3.12.5
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
callbacks:
    value:
        - lib: src.utils
          name: WandBCallback
          params:
            labels:
                - no 3
                - "3"
datamodule:
    value:
        batch_size: 25
        path: dataset
logger:
    value: WandbLogger
logger_params:
    value:
        name: "005"
        project: dlops-mnist
trainer:
    value:
        callbacks:
            - <src.utils.WandBCallback object at 0x0000015330D5EAB0>
            - <pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar object at 0x0000015330D5EED0>
            - <pytorch_lightning.callbacks.model_summary.ModelSummary object at 0x0000015330D5EFF0>
        enable_checkpointing: false
        logger: <pytorch_lightning.loggers.wandb.WandbLogger object at 0x000001532EA9CBF0>
        max_epochs: 10
        overfit_batches: 0
